services:
  vertd:
    container_name: vertd
    image: ghcr.io/vert-sh/vertd:latest
    build: .
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_PINGS=${WEBHOOK_PINGS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - PUBLIC_URL=${PUBLIC_URL}
    ports:
      - "${PORT:-24153}:24153"

    # For AMD/Intel GPUs, uncomment the "devices" section - then remove
    # or comment out the "deploy" section and the "runtime" string used
    # for NVIDIA GPUs.
    #
    # devices:
    #   - /dev/dri
    #
    # For NVIDIA cards, keep the following section:
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
